./send.sh git@github.com:Microsoft/CNTK.git
./send.sh git@github.com:Microsoft/vscode.git
./send.sh git@github.com:apache/abdera.git
./send.sh git@github.com:apache/accumulo-bsp.git
./send.sh git@github.com:apache/accumulo-examples.git
./send.sh git@github.com:apache/accumulo-instamo-archetype.git
./send.sh git@github.com:apache/accumulo-pig.git
./send.sh git@github.com:apache/accumulo-testing.git
./send.sh git@github.com:apache/accumulo-website.git
./send.sh git@github.com:apache/accumulo-wikisearch.git
./send.sh git@github.com:apache/accumulo.git
./send.sh git@github.com:apache/ace.git
./send.sh git@github.com:apache/activemq-activeio.git
./send.sh git@github.com:apache/activemq-apollo.git
./send.sh git@github.com:apache/activemq-artemis.git
./send.sh git@github.com:apache/activemq-cpp.git
./send.sh git@github.com:apache/activemq-openwire.git
./send.sh git@github.com:apache/activemq-protobuf.git
./send.sh git@github.com:apache/activemq-stomp.git
./send.sh git@github.com:apache/activemq.git
./send.sh git@github.com:apache/airavata-docs.git
./send.sh git@github.com:apache/airavata-labs.git
./send.sh git@github.com:apache/airavata-php-gateway.git
./send.sh git@github.com:apache/airavata-sandbox.git
./send.sh git@github.com:apache/airavata-site.git
./send.sh git@github.com:apache/airavata.git
./send.sh git@github.com:apache/allura.git
./send.sh git@github.com:apache/ambari.git
./send.sh git@github.com:apache/ant-antlibs-antunit.git
./send.sh git@github.com:apache/ant-antlibs-common.git
./send.sh git@github.com:apache/ant-antlibs-compress.git
./send.sh git@github.com:apache/ant-antlibs-dotnet.git
./send.sh git@github.com:apache/ant-antlibs-props.git
./send.sh git@github.com:apache/ant-antlibs-svn.git
./send.sh git@github.com:apache/ant-antlibs-vss.git
./send.sh git@github.com:apache/ant-easyant-buildtypes.git
./send.sh git@github.com:apache/ant-easyant-core.git
./send.sh git@github.com:apache/ant-easyant-easyant4e.git
./send.sh git@github.com:apache/ant-easyant-plugins.git
./send.sh git@github.com:apache/ant-easyant-skeletons.git
./send.sh git@github.com:apache/ant-easyant-tasks.git
./send.sh git@github.com:apache/ant-ivy.git
./send.sh git@github.com:apache/ant-ivyde.git
./send.sh git@github.com:apache/ant-xooki.git
./send.sh git@github.com:apache/ant.git
./send.sh git@github.com:apache/any23.git
./send.sh git@github.com:apache/apache-website-template.git
./send.sh git@github.com:apache/apex-core.git
./send.sh git@github.com:apache/apex-malhar.git
./send.sh git@github.com:apache/apex-site.git
./send.sh git@github.com:apache/apr-iconv.git
./send.sh git@github.com:apache/apr-util.git
./send.sh git@github.com:apache/apr.git
./send.sh git@github.com:apache/apreq.git
./send.sh git@github.com:apache/archiva-redback-core.git
./send.sh git@github.com:apache/archiva-sandbox.git
./send.sh git@github.com:apache/archiva-site.git
./send.sh git@github.com:apache/archiva.git
./send.sh git@github.com:apache/aries-jax-rs-whiteboard.git
./send.sh git@github.com:apache/aries-rsa.git
./send.sh git@github.com:apache/aries.git
./send.sh git@github.com:apache/arrow-site.git
./send.sh git@github.com:apache/arrow.git
./send.sh git@github.com:apache/asterixdb-bad.git
./send.sh git@github.com:apache/asterixdb-site.git
./send.sh git@github.com:apache/asterixdb.git
./send.sh git@github.com:apache/aurora-packaging.git
./send.sh git@github.com:apache/aurora-website.git
./send.sh git@github.com:apache/aurora.git
./send.sh git@github.com:apache/avro.git
./send.sh git@github.com:apache/axis1-java.git
./send.sh git@github.com:apache/axis1.git
./send.sh git@github.com:apache/axis2-c.git
./send.sh git@github.com:apache/axis2-java.git
./send.sh git@github.com:apache/axis2-transports.git
./send.sh git@github.com:apache/bahir-flink.git
./send.sh git@github.com:apache/bahir-website.git
./send.sh git@github.com:apache/bahir.git
./send.sh git@github.com:apache/batik.git
./send.sh git@github.com:apache/beam-site.git
./send.sh git@github.com:apache/beam.git
./send.sh git@github.com:apache/bigtop.git
./send.sh git@github.com:apache/bloodhound.git
./send.sh git@github.com:apache/bookkeeper.git
./send.sh git@github.com:apache/brooklyn-client.git
./send.sh git@github.com:apache/brooklyn-dist.git
./send.sh git@github.com:apache/brooklyn-docs.git
./send.sh git@github.com:apache/brooklyn-library.git
./send.sh git@github.com:apache/brooklyn-server.git
./send.sh git@github.com:apache/brooklyn-ui.git
./send.sh git@github.com:apache/brooklyn.git
./send.sh git@github.com:apache/buildr.git
./send.sh git@github.com:apache/bval.git
./send.sh git@github.com:apache/calcite.git
./send.sh git@github.com:apache/camel.git
./send.sh git@github.com:apache/cassandra-builds.git
./send.sh git@github.com:apache/cassandra.git
./send.sh git@github.com:apache/cayenne-modeler.git
./send.sh git@github.com:apache/cayenne.git
./send.sh git@github.com:apache/celix.git
./send.sh git@github.com:apache/chainsaw.git
./send.sh git@github.com:apache/chemistry-cmislib.git
./send.sh git@github.com:apache/chemistry-dotcmis.git
./send.sh git@github.com:apache/chemistry-objectivecmis.git
./send.sh git@github.com:apache/chemistry-opencmis.git
./send.sh git@github.com:apache/chemistry-phpclient.git
./send.sh git@github.com:apache/chemistry-portcmis.git
./send.sh git@github.com:apache/chukwa.git
./send.sh git@github.com:apache/clerezza-rdf-core.git
./send.sh git@github.com:apache/clerezza.git
./send.sh git@github.com:apache/click.git
./send.sh git@github.com:apache/climate.git
./send.sh git@github.com:apache/cloudstack-cloudmonkey.git
./send.sh git@github.com:apache/cloudstack-docs-admin.git
./send.sh git@github.com:apache/cloudstack-docs-install.git
./send.sh git@github.com:apache/cloudstack-docs-rn.git
./send.sh git@github.com:apache/cloudstack-docs.git
./send.sh git@github.com:apache/cloudstack-ec2stack.git
./send.sh git@github.com:apache/cloudstack-gcestack.git
./send.sh git@github.com:apache/cloudstack-www.git
./send.sh git@github.com:apache/cloudstack.git
./send.sh git@github.com:apache/cocoon.git
./send.sh git@github.com:apache/commons-bcel.git
./send.sh git@github.com:apache/commons-beanutils.git
./send.sh git@github.com:apache/commons-bsf.git
./send.sh git@github.com:apache/commons-build-plugin.git
./send.sh git@github.com:apache/commons-chain.git
./send.sh git@github.com:apache/commons-cli.git
./send.sh git@github.com:apache/commons-codec.git
./send.sh git@github.com:apache/commons-collections.git
./send.sh git@github.com:apache/commons-complex.git
./send.sh git@github.com:apache/commons-compress.git
./send.sh git@github.com:apache/commons-configuration.git
./send.sh git@github.com:apache/commons-crypto.git
./send.sh git@github.com:apache/commons-csv.git
./send.sh git@github.com:apache/commons-daemon.git
./send.sh git@github.com:apache/commons-dbcp.git
./send.sh git@github.com:apache/commons-dbutils.git
./send.sh git@github.com:apache/commons-digester.git
./send.sh git@github.com:apache/commons-discovery.git
./send.sh git@github.com:apache/commons-email.git
./send.sh git@github.com:apache/commons-exec.git
./send.sh git@github.com:apache/commons-fileupload.git
./send.sh git@github.com:apache/commons-functor.git
./send.sh git@github.com:apache/commons-imaging.git
./send.sh git@github.com:apache/commons-io.git
./send.sh git@github.com:apache/commons-jci.git
./send.sh git@github.com:apache/commons-jcs.git
./send.sh git@github.com:apache/commons-jelly.git
./send.sh git@github.com:apache/commons-jexl.git
./send.sh git@github.com:apache/commons-jxpath.git
./send.sh git@github.com:apache/commons-lang.git
./send.sh git@github.com:apache/commons-launcher.git
./send.sh git@github.com:apache/commons-logging.git
./send.sh git@github.com:apache/commons-math.git
./send.sh git@github.com:apache/commons-modeler.git
./send.sh git@github.com:apache/commons-net.git
./send.sh git@github.com:apache/commons-ognl.git
./send.sh git@github.com:apache/commons-pool.git
./send.sh git@github.com:apache/commons-proxy.git
./send.sh git@github.com:apache/commons-rdf.git
./send.sh git@github.com:apache/commons-rng.git
./send.sh git@github.com:apache/commons-scxml.git
./send.sh git@github.com:apache/commons-text.git
./send.sh git@github.com:apache/commons-transaction.git
./send.sh git@github.com:apache/commons-validator.git
./send.sh git@github.com:apache/commons-vfs.git
./send.sh git@github.com:apache/commons-weaver.git
./send.sh git@github.com:apache/continuum.git
./send.sh git@github.com:apache/cordova-amazon-fireos.git
./send.sh git@github.com:apache/cordova-android.git
./send.sh git@github.com:apache/cordova-app-harness.git
./send.sh git@github.com:apache/cordova-app-hello-world.git
./send.sh git@github.com:apache/cordova-bada-wac.git
./send.sh git@github.com:apache/cordova-bada.git
./send.sh git@github.com:apache/cordova-blackberry.git
./send.sh git@github.com:apache/cordova-browser.git
./send.sh git@github.com:apache/cordova-cli.git
./send.sh git@github.com:apache/cordova-coho.git
./send.sh git@github.com:apache/cordova-common.git
./send.sh git@github.com:apache/cordova-create.git
./send.sh git@github.com:apache/cordova-docs.git
./send.sh git@github.com:apache/cordova-electron.git
./send.sh git@github.com:apache/cordova-fauxton-server.git
./send.sh git@github.com:apache/cordova-fetch.git
./send.sh git@github.com:apache/cordova-firefoxos.git
./send.sh git@github.com:apache/cordova-ios.git
./send.sh git@github.com:apache/cordova-js.git
./send.sh git@github.com:apache/cordova-labs.git
./send.sh git@github.com:apache/cordova-lib.git
./send.sh git@github.com:apache/cordova-medic.git
./send.sh git@github.com:apache/cordova-mobile-spec.git
./send.sh git@github.com:apache/cordova-osx.git
./send.sh git@github.com:apache/cordova-paramedic.git
./send.sh git@github.com:apache/cordova-plugin-battery-status.git
./send.sh git@github.com:apache/cordova-plugin-camera.git
./send.sh git@github.com:apache/cordova-plugin-compat.git
./send.sh git@github.com:apache/cordova-plugin-console.git
./send.sh git@github.com:apache/cordova-plugin-contacts.git
./send.sh git@github.com:apache/cordova-plugin-device-motion.git
./send.sh git@github.com:apache/cordova-plugin-device-orientation.git
./send.sh git@github.com:apache/cordova-plugin-device.git
./send.sh git@github.com:apache/cordova-plugin-dialogs.git
./send.sh git@github.com:apache/cordova-plugin-file-transfer.git
./send.sh git@github.com:apache/cordova-plugin-file.git
./send.sh git@github.com:apache/cordova-plugin-geolocation.git
./send.sh git@github.com:apache/cordova-plugin-globalization.git
./send.sh git@github.com:apache/cordova-plugin-inappbrowser.git
./send.sh git@github.com:apache/cordova-plugin-legacy-whitelist.git
./send.sh git@github.com:apache/cordova-plugin-media-capture.git
./send.sh git@github.com:apache/cordova-plugin-media.git
./send.sh git@github.com:apache/cordova-plugin-network-information.git
./send.sh git@github.com:apache/cordova-plugin-screen-orientation.git
./send.sh git@github.com:apache/cordova-plugin-splashscreen.git
./send.sh git@github.com:apache/cordova-plugin-statusbar.git
./send.sh git@github.com:apache/cordova-plugin-test-framework.git
./send.sh git@github.com:apache/cordova-plugin-vibration.git
./send.sh git@github.com:apache/cordova-plugin-whitelist.git
./send.sh git@github.com:apache/cordova-plugin-wkwebview-engine.git
./send.sh git@github.com:apache/cordova-plugins.git
./send.sh git@github.com:apache/cordova-plugman.git
./send.sh git@github.com:apache/cordova-qt.git
./send.sh git@github.com:apache/cordova-registry-web.git
./send.sh git@github.com:apache/cordova-registry.git
./send.sh git@github.com:apache/cordova-serve.git
./send.sh git@github.com:apache/cordova-template-reference.git
./send.sh git@github.com:apache/cordova-tizen.git
./send.sh git@github.com:apache/cordova-ubuntu.git
./send.sh git@github.com:apache/cordova-webos.git
./send.sh git@github.com:apache/cordova-weinre.git
./send.sh git@github.com:apache/cordova-windows.git
./send.sh git@github.com:apache/cordova-wp7.git
./send.sh git@github.com:apache/cordova-wp8.git
./send.sh git@github.com:apache/couchdb-admin.git
./send.sh git@github.com:apache/couchdb-b64url.git
./send.sh git@github.com:apache/couchdb-bear.git
./send.sh git@github.com:apache/couchdb-cassim.git
./send.sh git@github.com:apache/couchdb-chttpd.git
./send.sh git@github.com:apache/couchdb-ci.git
./send.sh git@github.com:apache/couchdb-config.git
./send.sh git@github.com:apache/couchdb-couch-collate.git
./send.sh git@github.com:apache/couchdb-couch-dbupdates.git
./send.sh git@github.com:apache/couchdb-couch-epi.git
./send.sh git@github.com:apache/couchdb-couch-event.git
./send.sh git@github.com:apache/couchdb-couch-httpd.git
./send.sh git@github.com:apache/couchdb-couch-index.git
./send.sh git@github.com:apache/couchdb-couch-log-lager.git
./send.sh git@github.com:apache/couchdb-couch-log.git
./send.sh git@github.com:apache/couchdb-couch-mrview.git
./send.sh git@github.com:apache/couchdb-couch-plugins.git
./send.sh git@github.com:apache/couchdb-couch-replicator.git
./send.sh git@github.com:apache/couchdb-couch-stats.git
./send.sh git@github.com:apache/couchdb-couch.git
./send.sh git@github.com:apache/couchdb-ddoc-cache.git
./send.sh git@github.com:apache/couchdb-docker.git
./send.sh git@github.com:apache/couchdb-documentation.git
./send.sh git@github.com:apache/couchdb-erlang-tests.git
./send.sh git@github.com:apache/couchdb-ets-lru.git
./send.sh git@github.com:apache/couchdb-examples.git
./send.sh git@github.com:apache/couchdb-fabric.git
./send.sh git@github.com:apache/couchdb-fauxton-server.git
./send.sh git@github.com:apache/couchdb-fauxton.git
./send.sh git@github.com:apache/couchdb-folsom.git
./send.sh git@github.com:apache/couchdb-futon.git
./send.sh git@github.com:apache/couchdb-glazier.git
./send.sh git@github.com:apache/couchdb-global-changes.git
./send.sh git@github.com:apache/couchdb-goldrush.git
./send.sh git@github.com:apache/couchdb-ibrowse.git
./send.sh git@github.com:apache/couchdb-ioq.git
./send.sh git@github.com:apache/couchdb-javascript-tests.git
./send.sh git@github.com:apache/couchdb-jiffy.git
./send.sh git@github.com:apache/couchdb-jquery-couch.git
./send.sh git@github.com:apache/couchdb-khash.git
./send.sh git@github.com:apache/couchdb-lager.git
./send.sh git@github.com:apache/couchdb-mango.git
./send.sh git@github.com:apache/couchdb-meck.git
./send.sh git@github.com:apache/couchdb-mem3.git
./send.sh git@github.com:apache/couchdb-mochiweb.git
./send.sh git@github.com:apache/couchdb-nano.git
./send.sh git@github.com:apache/couchdb-nmo.git
./send.sh git@github.com:apache/couchdb-oauth.git
./send.sh git@github.com:apache/couchdb-peruser.git
./send.sh git@github.com:apache/couchdb-query-server-node.git
./send.sh git@github.com:apache/couchdb-query-server-spidermonkey.git
./send.sh git@github.com:apache/couchdb-rebar.git
./send.sh git@github.com:apache/couchdb-rexi.git
./send.sh git@github.com:apache/couchdb-setup.git
./send.sh git@github.com:apache/couchdb-snappy.git
./send.sh git@github.com:apache/couchdb-twig.git
./send.sh git@github.com:apache/couchdb-www.git
./send.sh git@github.com:apache/couchdb.git
./send.sh git@github.com:apache/creadur-rat.git
./send.sh git@github.com:apache/creadur-site.git
./send.sh git@github.com:apache/creadur-tentacles.git
./send.sh git@github.com:apache/creadur-whisker.git
./send.sh git@github.com:apache/crunch.git
./send.sh git@github.com:apache/ctakes.git
./send.sh git@github.com:apache/curator.git
./send.sh git@github.com:apache/cxf-build-utils.git
./send.sh git@github.com:apache/cxf-dosgi.git
./send.sh git@github.com:apache/cxf-fediz.git
./send.sh git@github.com:apache/cxf-xjc-utils.git
./send.sh git@github.com:apache/cxf.git
./send.sh git@github.com:apache/ddlutils.git
./send.sh git@github.com:apache/deltacloud.git
./send.sh git@github.com:apache/deltaspike.git
./send.sh git@github.com:apache/derby.git
./send.sh git@github.com:apache/devicemap-browsermap.git
./send.sh git@github.com:apache/directmemory-lightning.git
./send.sh git@github.com:apache/directmemory.git
./send.sh git@github.com:apache/directory-clients.git
./send.sh git@github.com:apache/directory-daemon.git
./send.sh git@github.com:apache/directory-fortress-commander.git
./send.sh git@github.com:apache/directory-fortress-core.git
./send.sh git@github.com:apache/directory-fortress-enmasse.git
./send.sh git@github.com:apache/directory-fortress-realm.git
./send.sh git@github.com:apache/directory-installers.git
./send.sh git@github.com:apache/directory-kerby.git
./send.sh git@github.com:apache/directory-project.git
./send.sh git@github.com:apache/directory-samples.git
./send.sh git@github.com:apache/directory-server.git
./send.sh git@github.com:apache/directory-shared.git
./send.sh git@github.com:apache/directory-skins.git
./send.sh git@github.com:apache/directory-studio-plugin.git
./send.sh git@github.com:apache/directory-studio.git
./send.sh git@github.com:apache/drill-site.git
./send.sh git@github.com:apache/drill.git
./send.sh git@github.com:apache/eagle.git
./send.sh git@github.com:apache/empire-db.git
./send.sh git@github.com:apache/esme.git
./send.sh git@github.com:apache/etch.git
./send.sh git@github.com:apache/falcon.git
./send.sh git@github.com:apache/felix.git
./send.sh git@github.com:apache/flex-asjs.git
./send.sh git@github.com:apache/flex-blazeds.git
./send.sh git@github.com:apache/flex-examples.git
./send.sh git@github.com:apache/flex-external.git
./send.sh git@github.com:apache/flex-falcon.git
./send.sh git@github.com:apache/flex-flexunit.git
./send.sh git@github.com:apache/flex-sdk.git
./send.sh git@github.com:apache/flex-site.git
./send.sh git@github.com:apache/flex-tlf.git
./send.sh git@github.com:apache/flex-tourjs.git
./send.sh git@github.com:apache/flex-typedefs.git
./send.sh git@github.com:apache/flex-utilities.git
./send.sh git@github.com:apache/flex-whiteboard.git
./send.sh git@github.com:apache/flink-web.git
./send.sh git@github.com:apache/flink.git
./send.sh git@github.com:apache/flood.git
./send.sh git@github.com:apache/flume.git
./send.sh git@github.com:apache/fop-pdf-images.git
./send.sh git@github.com:apache/fop.git
./send.sh git@github.com:apache/forrest.git
./send.sh git@github.com:apache/ftpserver.git
./send.sh git@github.com:apache/geode-examples.git
./send.sh git@github.com:apache/geode.git
./send.sh git@github.com:apache/geronimo-devtools.git
./send.sh git@github.com:apache/geronimo-genesis.git
./send.sh git@github.com:apache/geronimo-gshell.git
./send.sh git@github.com:apache/geronimo-jaspi.git
./send.sh git@github.com:apache/geronimo-javamail.git
./send.sh git@github.com:apache/geronimo-schema-14.git
./send.sh git@github.com:apache/geronimo-schema-5.git
./send.sh git@github.com:apache/geronimo-schema-6.git
./send.sh git@github.com:apache/geronimo-specs.git
./send.sh git@github.com:apache/geronimo-txmanager.git
./send.sh git@github.com:apache/geronimo-xbean.git
./send.sh git@github.com:apache/geronimo-yoko.git
./send.sh git@github.com:apache/geronimo.git
./send.sh git@github.com:apache/giraph.git
./send.sh git@github.com:apache/gora.git
./send.sh git@github.com:apache/groovy.git
./send.sh git@github.com:apache/hadoop-common.git
./send.sh git@github.com:apache/hadoop-hdfs.git
./send.sh git@github.com:apache/hadoop-mapreduce.git
./send.sh git@github.com:apache/hadoop.git
./send.sh git@github.com:apache/hama.git
./send.sh git@github.com:apache/harmony.git
./send.sh git@github.com:apache/hbase.git
./send.sh git@github.com:apache/hcatalog.git
./send.sh git@github.com:apache/helix.git
./send.sh git@github.com:apache/hive.git
./send.sh git@github.com:apache/httpasyncclient.git
./send.sh git@github.com:apache/httpclient.git
./send.sh git@github.com:apache/httpcore.git
./send.sh git@github.com:apache/httpd-docs-build.git
./send.sh git@github.com:apache/httpd.git
./send.sh git@github.com:apache/iampoc.git
./send.sh git@github.com:apache/ignite.git
./send.sh git@github.com:apache/incubator-airflow.git
./send.sh git@github.com:apache/incubator-annotator-website.git
./send.sh git@github.com:apache/incubator-annotator.git
./send.sh git@github.com:apache/incubator-ariatosca-website.git
./send.sh git@github.com:apache/incubator-ariatosca.git
./send.sh git@github.com:apache/incubator-asterixdb-hyracks.git
./send.sh git@github.com:apache/incubator-atlas.git
./send.sh git@github.com:apache/incubator-batchee.git
./send.sh git@github.com:apache/incubator-blur.git
./send.sh git@github.com:apache/incubator-brooklyn-site.git
./send.sh git@github.com:apache/incubator-brooklyn.git
./send.sh git@github.com:apache/incubator-carbondata-site.git
./send.sh git@github.com:apache/incubator-carbondata.git
./send.sh git@github.com:apache/incubator-concerted.git
./send.sh git@github.com:apache/incubator-corinthia.git
./send.sh git@github.com:apache/incubator-cotton.git
./send.sh git@github.com:apache/incubator-datafu.git
./send.sh git@github.com:apache/incubator-distributedlog.git
./send.sh git@github.com:apache/incubator-edgent-website.git
./send.sh git@github.com:apache/incubator-edgent.git
./send.sh git@github.com:apache/incubator-fineract-site.git
./send.sh git@github.com:apache/incubator-fineract.git
./send.sh git@github.com:apache/incubator-fluo-recipes.git
./send.sh git@github.com:apache/incubator-fluo-website.git
./send.sh git@github.com:apache/incubator-fluo.git
./send.sh git@github.com:apache/incubator-freemarker-docgen.git
./send.sh git@github.com:apache/incubator-freemarker-site.git
./send.sh git@github.com:apache/incubator-freemarker.git
./send.sh git@github.com:apache/incubator-gearpump-site.git
./send.sh git@github.com:apache/incubator-gearpump.git
./send.sh git@github.com:apache/incubator-gossip.git
./send.sh git@github.com:apache/incubator-guacamole-client.git
./send.sh git@github.com:apache/incubator-guacamole-manual.git
./send.sh git@github.com:apache/incubator-guacamole-server.git
./send.sh git@github.com:apache/incubator-guacamole-website.git
./send.sh git@github.com:apache/incubator-hawq-docs.git
./send.sh git@github.com:apache/incubator-hawq-site.git
./send.sh git@github.com:apache/incubator-hawq.git
./send.sh git@github.com:apache/incubator-hdt.git
./send.sh git@github.com:apache/incubator-hivemall-site.git
./send.sh git@github.com:apache/incubator-hivemall.git
./send.sh git@github.com:apache/incubator-horn-site.git
./send.sh git@github.com:apache/incubator-horn.git
./send.sh git@github.com:apache/incubator-htrace.git
./send.sh git@github.com:apache/incubator-impala.git
./send.sh git@github.com:apache/incubator-iota-site.git
./send.sh git@github.com:apache/incubator-iota.git
./send.sh git@github.com:apache/incubator-joshua.git
./send.sh git@github.com:apache/incubator-juneau-website.git
./send.sh git@github.com:apache/incubator-juneau.git
./send.sh git@github.com:apache/incubator-madlib-site.git
./send.sh git@github.com:apache/incubator-madlib.git
./send.sh git@github.com:apache/incubator-metron.git
./send.sh git@github.com:apache/incubator-milagro-crypto.git
./send.sh git@github.com:apache/incubator-milagro-mfa-js-client.git
./send.sh git@github.com:apache/incubator-milagro-mfa-js-lib.git
./send.sh git@github.com:apache/incubator-milagro-mfa-sdk-android.git
./send.sh git@github.com:apache/incubator-milagro-mfa-sdk-core.git
./send.sh git@github.com:apache/incubator-milagro-mfa-sdk-ios.git
./send.sh git@github.com:apache/incubator-milagro-mfa-sdk-wp.git
./send.sh git@github.com:apache/incubator-milagro-mfa-server.git
./send.sh git@github.com:apache/incubator-milagro-tls.git
./send.sh git@github.com:apache/incubator-milagro.git
./send.sh git@github.com:apache/incubator-mnemonic.git
./send.sh git@github.com:apache/incubator-mrql.git
./send.sh git@github.com:apache/incubator-mynewt-blinky.git
./send.sh git@github.com:apache/incubator-mynewt-core.git
./send.sh git@github.com:apache/incubator-mynewt-documentation.git
./send.sh git@github.com:apache/incubator-mynewt-newt.git
./send.sh git@github.com:apache/incubator-mynewt-newtmgr.git
./send.sh git@github.com:apache/incubator-mynewt-pkg-bsp.git
./send.sh git@github.com:apache/incubator-mynewt-pkg-pkg.git
./send.sh git@github.com:apache/incubator-mynewt-pkg-sdk.git
./send.sh git@github.com:apache/incubator-mynewt-site.git
./send.sh git@github.com:apache/incubator-myriad.git
./send.sh git@github.com:apache/incubator-netbeans-temp.git
./send.sh git@github.com:apache/incubator-netbeans-website.git
./send.sh git@github.com:apache/incubator-omid.git
./send.sh git@github.com:apache/incubator-openaz-site.git
./send.sh git@github.com:apache/incubator-openaz.git
./send.sh git@github.com:apache/incubator-optiq-csv.git
./send.sh git@github.com:apache/incubator-optiq-linq4j.git
./send.sh git@github.com:apache/incubator-pirk.git
./send.sh git@github.com:apache/incubator-ponymail-site.git
./send.sh git@github.com:apache/incubator-ponymail.git
./send.sh git@github.com:apache/incubator-predictionio-sdk-java.git
./send.sh git@github.com:apache/incubator-predictionio-sdk-php.git
./send.sh git@github.com:apache/incubator-predictionio-sdk-python.git
./send.sh git@github.com:apache/incubator-predictionio-sdk-ruby.git
./send.sh git@github.com:apache/incubator-predictionio-sdk-swift.git
./send.sh git@github.com:apache/incubator-predictionio-template-attribute-based-classifier.git
./send.sh git@github.com:apache/incubator-predictionio-template-ecom-recommender.git
./send.sh git@github.com:apache/incubator-predictionio-template-java-ecom-recommender.git
./send.sh git@github.com:apache/incubator-predictionio-template-recommender.git
./send.sh git@github.com:apache/incubator-predictionio-template-similar-product.git
./send.sh git@github.com:apache/incubator-predictionio-template-skeleton.git
./send.sh git@github.com:apache/incubator-predictionio-template-text-classifier.git
./send.sh git@github.com:apache/incubator-predictionio.git
./send.sh git@github.com:apache/incubator-provisionr.git
./send.sh git@github.com:apache/incubator-quickstep-site.git
./send.sh git@github.com:apache/incubator-quickstep.git
./send.sh git@github.com:apache/incubator-ranger.git
./send.sh git@github.com:apache/incubator-ripple.git
./send.sh git@github.com:apache/incubator-rocketmq-site.git
./send.sh git@github.com:apache/incubator-rocketmq.git
./send.sh git@github.com:apache/incubator-rya-site.git
./send.sh git@github.com:apache/incubator-rya.git
./send.sh git@github.com:apache/incubator-s2graph.git
./send.sh git@github.com:apache/incubator-s4.git
./send.sh git@github.com:apache/incubator-samoa.git
./send.sh git@github.com:apache/incubator-senssoft-distill.git
./send.sh git@github.com:apache/incubator-senssoft-stout.git
./send.sh git@github.com:apache/incubator-senssoft-tap.git
./send.sh git@github.com:apache/incubator-senssoft-user-ale.git
./send.sh git@github.com:apache/incubator-senssoft-userale-pyqt5.git
./send.sh git@github.com:apache/incubator-senssoft-useralejs.git
./send.sh git@github.com:apache/incubator-senssoft.git
./send.sh git@github.com:apache/incubator-sentry.git
./send.sh git@github.com:apache/incubator-singa.git
./send.sh git@github.com:apache/incubator-slider.git
./send.sh git@github.com:apache/incubator-spot.git
./send.sh git@github.com:apache/incubator-streams-examples.git
./send.sh git@github.com:apache/incubator-streams-master.git
./send.sh git@github.com:apache/incubator-streams.git
./send.sh git@github.com:apache/incubator-systemml-website.git
./send.sh git@github.com:apache/incubator-systemml.git
./send.sh git@github.com:apache/incubator-tamaya-extensions.git
./send.sh git@github.com:apache/incubator-tamaya-sandbox.git
./send.sh git@github.com:apache/incubator-tamaya-site.git
./send.sh git@github.com:apache/incubator-tamaya.git
./send.sh git@github.com:apache/incubator-taverna-commandline.git
./send.sh git@github.com:apache/incubator-taverna-common-activities.git
./send.sh git@github.com:apache/incubator-taverna-databundle-viewer.git
./send.sh git@github.com:apache/incubator-taverna-engine.git
./send.sh git@github.com:apache/incubator-taverna-language.git
./send.sh git@github.com:apache/incubator-taverna-maven-parent.git
./send.sh git@github.com:apache/incubator-taverna-mobile.git
./send.sh git@github.com:apache/incubator-taverna-osgi.git
./send.sh git@github.com:apache/incubator-taverna-plugin-bioinformatics.git
./send.sh git@github.com:apache/incubator-taverna-plugin-component.git
./send.sh git@github.com:apache/incubator-taverna-plugin-gis.git
./send.sh git@github.com:apache/incubator-taverna-server.git
./send.sh git@github.com:apache/incubator-taverna-site.git
./send.sh git@github.com:apache/incubator-taverna-workbench-common-activities.git
./send.sh git@github.com:apache/incubator-taverna-workbench-product.git
./send.sh git@github.com:apache/incubator-taverna-workbench.git
./send.sh git@github.com:apache/incubator-tephra.git
./send.sh git@github.com:apache/incubator-toree-website.git
./send.sh git@github.com:apache/incubator-toree.git
./send.sh git@github.com:apache/incubator-trafficcontrol.git
./send.sh git@github.com:apache/incubator-trafodion.git
./send.sh git@github.com:apache/incubator-twill.git
./send.sh git@github.com:apache/incubator-unomi.git
./send.sh git@github.com:apache/incubator-wave-android.git
./send.sh git@github.com:apache/incubator-wave-docs.git
./send.sh git@github.com:apache/incubator-wave.git
./send.sh git@github.com:apache/incubator-weex.git
./send.sh git@github.com:apache/incubator.git
./send.sh git@github.com:apache/infrastructure-docker.git
./send.sh git@github.com:apache/infrastructure-mergebot-test.git
./send.sh git@github.com:apache/infrastructure-packer.git
./send.sh git@github.com:apache/infrastructure-puppet-kitchen.git
./send.sh git@github.com:apache/infrastructure-puppet.git
./send.sh git@github.com:apache/infrastructure-website.git
./send.sh git@github.com:apache/infrastructure-whimsy.git
./send.sh git@github.com:apache/isis.git
./send.sh git@github.com:apache/jackrabbit-filevault.git
./send.sh git@github.com:apache/jackrabbit-oak.git
./send.sh git@github.com:apache/jackrabbit-ocm.git
./send.sh git@github.com:apache/jackrabbit.git
./send.sh git@github.com:apache/james-hupa.git
./send.sh git@github.com:apache/james-jdkim.git
./send.sh git@github.com:apache/james-jsieve.git
./send.sh git@github.com:apache/james-jspf.git
./send.sh git@github.com:apache/james-mime4j.git
./send.sh git@github.com:apache/james-postage.git
./send.sh git@github.com:apache/james-project.git
./send.sh git@github.com:apache/jclouds.git
./send.sh git@github.com:apache/jena.git
./send.sh git@github.com:apache/jmeter.git
./send.sh git@github.com:apache/johnzon.git
./send.sh git@github.com:apache/jspwiki-asf-docs.git
./send.sh git@github.com:apache/jspwiki.git
./send.sh git@github.com:apache/juddi-scout.git
./send.sh git@github.com:apache/juddi-styles.git
./send.sh git@github.com:apache/juddi.git
./send.sh git@github.com:apache/kafka-site.git
./send.sh git@github.com:apache/kafka.git
./send.sh git@github.com:apache/kalumet.git
./send.sh git@github.com:apache/kandula.git
./send.sh git@github.com:apache/karaf-boot.git
./send.sh git@github.com:apache/karaf-cave.git
./send.sh git@github.com:apache/karaf-cellar.git
./send.sh git@github.com:apache/karaf-decanter.git
./send.sh git@github.com:apache/karaf-eik.git
./send.sh git@github.com:apache/karaf-site.git
./send.sh git@github.com:apache/karaf-webconsole.git
./send.sh git@github.com:apache/karaf.git
./send.sh git@github.com:apache/knox.git
./send.sh git@github.com:apache/kudu.git
./send.sh git@github.com:apache/kylin.git
./send.sh git@github.com:apache/lens.git
./send.sh git@github.com:apache/lenya.git
./send.sh git@github.com:apache/libcloud.git
./send.sh git@github.com:apache/log4cxx.git
./send.sh git@github.com:apache/log4j-component.git
./send.sh git@github.com:apache/log4j-extras.git
./send.sh git@github.com:apache/log4j-receivers.git
./send.sh git@github.com:apache/log4j-zeroconf.git
./send.sh git@github.com:apache/log4j.git
./send.sh git@github.com:apache/log4net.git
./send.sh git@github.com:apache/logging-log4j-audit.git
./send.sh git@github.com:apache/logging-log4j-boot.git
./send.sh git@github.com:apache/logging-log4j-kotlin.git
./send.sh git@github.com:apache/logging-log4j-plugins.git
./send.sh git@github.com:apache/logging-log4j-scala.git
./send.sh git@github.com:apache/logging-log4j-tools.git
./send.sh git@github.com:apache/logging-log4j2.git
./send.sh git@github.com:apache/logging-log4php.git
./send.sh git@github.com:apache/lucene-solr.git
./send.sh git@github.com:apache/lucenenet.git
./send.sh git@github.com:apache/lucy-charmonizer.git
./send.sh git@github.com:apache/lucy-clownfish.git
./send.sh git@github.com:apache/lucy.git
./send.sh git@github.com:apache/mahout.git
./send.sh git@github.com:apache/manifoldcf-integration-sharepoint-2007.git
./send.sh git@github.com:apache/manifoldcf-integration-sharepoint-2010.git
./send.sh git@github.com:apache/manifoldcf-integration-solr-3.x.git
./send.sh git@github.com:apache/manifoldcf-integration-solr-4.x.git
./send.sh git@github.com:apache/manifoldcf.git
./send.sh git@github.com:apache/marmotta.git
./send.sh git@github.com:apache/maven-2.git
./send.sh git@github.com:apache/maven-ant-tasks.git
./send.sh git@github.com:apache/maven-app-engine.git
./send.sh git@github.com:apache/maven-archetype.git
./send.sh git@github.com:apache/maven-doxia-sitetools.git
./send.sh git@github.com:apache/maven-doxia-tools.git
./send.sh git@github.com:apache/maven-doxia.git
./send.sh git@github.com:apache/maven-enforcer.git
./send.sh git@github.com:apache/maven-indexer.git
./send.sh git@github.com:apache/maven-integration-testing.git
./send.sh git@github.com:apache/maven-jxr.git
./send.sh git@github.com:apache/maven-mercury.git
./send.sh git@github.com:apache/maven-plugin-testing.git
./send.sh git@github.com:apache/maven-plugin-tools.git
./send.sh git@github.com:apache/maven-plugins.git
./send.sh git@github.com:apache/maven-pom.git
./send.sh git@github.com:apache/maven-release.git
./send.sh git@github.com:apache/maven-repository-tools.git
./send.sh git@github.com:apache/maven-resolver.git
./send.sh git@github.com:apache/maven-resources.git
./send.sh git@github.com:apache/maven-sandbox.git
./send.sh git@github.com:apache/maven-scm.git
./send.sh git@github.com:apache/maven-shared.git
./send.sh git@github.com:apache/maven-site.git
./send.sh git@github.com:apache/maven-skins.git
./send.sh git@github.com:apache/maven-surefire.git
./send.sh git@github.com:apache/maven-wagon.git
./send.sh git@github.com:apache/maven.git
./send.sh git@github.com:apache/meecrowave.git
./send.sh git@github.com:apache/mesos.git
./send.sh git@github.com:apache/metamodel.git
./send.sh git@github.com:apache/mina-sshd.git
./send.sh git@github.com:apache/mina.git
./send.sh git@github.com:apache/mod_perl.git
./send.sh git@github.com:apache/mrunit.git
./send.sh git@github.com:apache/myfaces-extcdi.git
./send.sh git@github.com:apache/myfaces-extval.git
./send.sh git@github.com:apache/myfaces-html5.git
./send.sh git@github.com:apache/myfaces-portlet-bridge.git
./send.sh git@github.com:apache/myfaces-scripting.git
./send.sh git@github.com:apache/myfaces.git
./send.sh git@github.com:apache/nifi-maven.git
./send.sh git@github.com:apache/nifi-minifi-cpp.git
./send.sh git@github.com:apache/nifi-minifi.git
./send.sh git@github.com:apache/nifi-site.git
./send.sh git@github.com:apache/nifi.git
./send.sh git@github.com:apache/npanday-its.git
./send.sh git@github.com:apache/npanday.git
./send.sh git@github.com:apache/nutch.git
./send.sh git@github.com:apache/nuvem.git
./send.sh git@github.com:apache/ode-console.git
./send.sh git@github.com:apache/ode-jacob.git
./send.sh git@github.com:apache/ode.git
./send.sh git@github.com:apache/odftoolkit.git
./send.sh git@github.com:apache/ofbiz.git
./send.sh git@github.com:apache/olingo-odata2.git
./send.sh git@github.com:apache/olingo-odata4-js.git
./send.sh git@github.com:apache/olingo-odata4.git
./send.sh git@github.com:apache/oltu.git
./send.sh git@github.com:apache/oodt.git
./send.sh git@github.com:apache/oozie.git
./send.sh git@github.com:apache/openejb.git
./send.sh git@github.com:apache/openjpa.git
./send.sh git@github.com:apache/openmeetings.git
./send.sh git@github.com:apache/opennlp-addons.git
./send.sh git@github.com:apache/opennlp-sandbox.git
./send.sh git@github.com:apache/opennlp-site.git
./send.sh git@github.com:apache/opennlp.git
./send.sh git@github.com:apache/openoffice.git
./send.sh git@github.com:apache/openwebbeans.git
./send.sh git@github.com:apache/orc.git
./send.sh git@github.com:apache/parquet-cpp.git
./send.sh git@github.com:apache/parquet-format.git
./send.sh git@github.com:apache/parquet-mr.git
./send.sh git@github.com:apache/pdfbox-docs.git
./send.sh git@github.com:apache/pdfbox-examples.git
./send.sh git@github.com:apache/pdfbox.git
./send.sh git@github.com:apache/phoenix.git
./send.sh git@github.com:apache/photark-mobile.git
./send.sh git@github.com:apache/photark.git
./send.sh git@github.com:apache/pig.git
./send.sh git@github.com:apache/pivot.git
./send.sh git@github.com:apache/pluto.git
./send.sh git@github.com:apache/poi.git
./send.sh git@github.com:apache/polygene-java.git
./send.sh git@github.com:apache/polygene-sandbox.git
./send.sh git@github.com:apache/polygene-website.git
./send.sh git@github.com:apache/portals-pluto.git
./send.sh git@github.com:apache/qpid-cpp.git
./send.sh git@github.com:apache/qpid-dispatch.git
./send.sh git@github.com:apache/qpid-java.git
./send.sh git@github.com:apache/qpid-jms.git
./send.sh git@github.com:apache/qpid-proton-j.git
./send.sh git@github.com:apache/qpid-proton.git
./send.sh git@github.com:apache/qpid-python.git
./send.sh git@github.com:apache/qpid.git
./send.sh git@github.com:apache/rampart.git
./send.sh git@github.com:apache/rat.git
./send.sh git@github.com:apache/rave.git
./send.sh git@github.com:apache/redback-components.git
./send.sh git@github.com:apache/reef.git
./send.sh git@github.com:apache/river-container.git
./send.sh git@github.com:apache/river.git
./send.sh git@github.com:apache/roller-website.git
./send.sh git@github.com:apache/roller.git
./send.sh git@github.com:apache/samza-hello-samza.git
./send.sh git@github.com:apache/samza.git
./send.sh git@github.com:apache/sandesha.git
./send.sh git@github.com:apache/sanselan.git
./send.sh git@github.com:apache/santuario-cpp.git
./send.sh git@github.com:apache/santuario-java.git
./send.sh git@github.com:apache/savan.git
./send.sh git@github.com:apache/sentry.git
./send.sh git@github.com:apache/serf.git
./send.sh git@github.com:apache/servicemix-archetypes.git
./send.sh git@github.com:apache/servicemix-bundles.git
./send.sh git@github.com:apache/servicemix-components.git
./send.sh git@github.com:apache/servicemix-documentation.git
./send.sh git@github.com:apache/servicemix-maven-plugins.git
./send.sh git@github.com:apache/servicemix-pom.git
./send.sh git@github.com:apache/servicemix-specs.git
./send.sh git@github.com:apache/servicemix-utils.git
./send.sh git@github.com:apache/servicemix-website.git
./send.sh git@github.com:apache/servicemix.git
./send.sh git@github.com:apache/servicemix3.git
./send.sh git@github.com:apache/servicemix4-bundles.git
./send.sh git@github.com:apache/servicemix4-features.git
./send.sh git@github.com:apache/servicemix4-kernel.git
./send.sh git@github.com:apache/servicemix4-legal.git
./send.sh git@github.com:apache/servicemix4-nmr.git
./send.sh git@github.com:apache/servicemix4-specs.git
./send.sh git@github.com:apache/servicemix5.git
./send.sh git@github.com:apache/shindig.git
./send.sh git@github.com:apache/shiro-site.git
./send.sh git@github.com:apache/shiro.git
./send.sh git@github.com:apache/sirona.git
./send.sh git@github.com:apache/sis.git
./send.sh git@github.com:apache/sling.git
./send.sh git@github.com:apache/spamassassin.git
./send.sh git@github.com:apache/spark-website.git
./send.sh git@github.com:apache/spark.git
./send.sh git@github.com:apache/sqoop.git
./send.sh git@github.com:apache/stanbol.git
./send.sh git@github.com:apache/stdcxx.git
./send.sh git@github.com:apache/steve.git
./send.sh git@github.com:apache/storm.git
./send.sh git@github.com:apache/stratos.git
./send.sh git@github.com:apache/struts-annotations.git
./send.sh git@github.com:apache/struts-archetypes.git
./send.sh git@github.com:apache/struts-archive.git
./send.sh git@github.com:apache/struts-examples.git
./send.sh git@github.com:apache/struts-master.git
./send.sh git@github.com:apache/struts-maven.git
./send.sh git@github.com:apache/struts-sandbox.git
./send.sh git@github.com:apache/struts-site.git
./send.sh git@github.com:apache/struts.git
./send.sh git@github.com:apache/subversion.git
./send.sh git@github.com:apache/synapse.git
./send.sh git@github.com:apache/syncope.git
./send.sh git@github.com:apache/tajo.git
./send.sh git@github.com:apache/tapestry-5.git
./send.sh git@github.com:apache/tapestry3.git
./send.sh git@github.com:apache/tapestry4.git
./send.sh git@github.com:apache/tashi.git
./send.sh git@github.com:apache/tez.git
./send.sh git@github.com:apache/thrift.git
./send.sh git@github.com:apache/tika.git
./send.sh git@github.com:apache/tiles-autotag.git
./send.sh git@github.com:apache/tiles-request.git
./send.sh git@github.com:apache/tiles.git
./send.sh git@github.com:apache/tinkerpop.git
./send.sh git@github.com:apache/tomcat-connectors.git
./send.sh git@github.com:apache/tomcat-maven-plugin.git
./send.sh git@github.com:apache/tomcat-native.git
./send.sh git@github.com:apache/tomcat.git
./send.sh git@github.com:apache/tomcat60.git
./send.sh git@github.com:apache/tomcat70.git
./send.sh git@github.com:apache/tomcat80.git
./send.sh git@github.com:apache/tomcat85.git
./send.sh git@github.com:apache/tomee-site.git
./send.sh git@github.com:apache/tomee.git
./send.sh git@github.com:apache/tuscany-das.git
./send.sh git@github.com:apache/tuscany-sca-1.x.git
./send.sh git@github.com:apache/tuscany-sca-2.x.git
./send.sh git@github.com:apache/tuscany-sca-cpp.git
./send.sh git@github.com:apache/tuscany-sdo.git
./send.sh git@github.com:apache/twill.git
./send.sh git@github.com:apache/uima-addons.git
./send.sh git@github.com:apache/uima-as.git
./send.sh git@github.com:apache/uima-build.git
./send.sh git@github.com:apache/uima-ducc.git
./send.sh git@github.com:apache/uima-ruta.git
./send.sh git@github.com:apache/uima-sandbox.git
./send.sh git@github.com:apache/uima-uimacpp.git
./send.sh git@github.com:apache/uima-uimafit.git
./send.sh git@github.com:apache/uima-uimaj.git
./send.sh git@github.com:apache/usergrid-android.git
./send.sh git@github.com:apache/usergrid-dotnet.git
./send.sh git@github.com:apache/usergrid-java.git
./send.sh git@github.com:apache/usergrid-javascript.git
./send.sh git@github.com:apache/usergrid-nodejs.git
./send.sh git@github.com:apache/usergrid-python.git
./send.sh git@github.com:apache/usergrid-qakka.git
./send.sh git@github.com:apache/usergrid-swift.git
./send.sh git@github.com:apache/usergrid.git
./send.sh git@github.com:apache/velocity-engine.git
./send.sh git@github.com:apache/velocity-tools.git
./send.sh git@github.com:apache/vxquery.git
./send.sh git@github.com:apache/vysper.git
./send.sh git@github.com:apache/webservices-axiom.git
./send.sh git@github.com:apache/webservices-commons-xmlschema.git
./send.sh git@github.com:apache/webservices-neethi.git
./send.sh git@github.com:apache/webservices-xmlschema.git
./send.sh git@github.com:apache/whirr.git
./send.sh git@github.com:apache/wicket-site.git
./send.sh git@github.com:apache/wicket.git
./send.sh git@github.com:apache/wink-website.git
./send.sh git@github.com:apache/wink.git
./send.sh git@github.com:apache/wookie.git
./send.sh git@github.com:apache/wss4j.git
./send.sh git@github.com:apache/xalan-c.git
./send.sh git@github.com:apache/xalan-j.git
./send.sh git@github.com:apache/xerces-c.git
./send.sh git@github.com:apache/xerces2-j.git
./send.sh git@github.com:apache/xml-graphics-commons.git
./send.sh git@github.com:apache/xmlbeans.git
./send.sh git@github.com:apache/yetus.git
./send.sh git@github.com:apache/zeppelin.git
./send.sh git@github.com:apache/zetacomponents.git
./send.sh git@github.com:apache/zookeeper.git
./send.sh 